<?php
$z[0]=Array("field","",256,275);
$z[0][4]['name']="title";
$z[1]=Array("include","",391,426);
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",458,490);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",629,661);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("field","",720,739);
$z[4][4]['name']="title";
$z[5]=Array("field","",759,815);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[6]=Array("field","",829,847);
$z[6][4]['name']="body";
$z[7]=Array("field","",881,908);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",932,955);
$z[8][4]['name']="id";
$z[9]=Array("field","",960,984);
$z[9][4]['name']="mid";
$z[10]=Array("global","",1122,1154);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("channel","\r\n  \r\n  <li class=\"center\"><a href=\"http://www.djjwz.com/news.html\">企业新闻</a></li>\r\n\r\n  ",1218,1364);
$z[12]=Array("global","",1454,1486);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a></li>\r\n",1643,1786);
$z[13][4]['row']="6";

?>