<?php
$z[0]=Array("global","",201,228);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",373,399);
$z[1][4]['name']="cfg_headTxt";
$z[2]=Array("global","",476,503);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			",558,725);
$z[3][4]['row']="7";
$z[3][4]['type']="top";
$z[4]=Array("type","\r\n	<img src=\"/dedeCopyXunmei/templets/xunmei/images/banner[field:id/].jpg\" width=\"980\" height=\"175\" alt=\"[field:typename/]\" />\r\n	",778,930);

?>