<?php
$z[0]=Array("global","",108,140);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",234,261);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",406,432);
$z[2][4]['name']="cfg_headTxt";
$z[3]=Array("global","",494,521);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			",576,743);
$z[4][4]['row']="7";
$z[4][4]['type']="top";

?>