<?php
$z[0]=Array("field","",256,275);
$z[0][4]['name']="title";
$z[1]=Array("global","",276,302);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",346,405);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",442,471);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",585,620);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",4290,4327);
$z[5][4]['filename']="footer.htm";

?>