<?php
$z[0]=Array("global","",256,282);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",326,356);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",393,420);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",729,756);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",901,927);
$z[4][4]['name']="cfg_headTxt";
$z[5]=Array("global","",1004,1031);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n			",1086,1253);
$z[6][4]['row']="7";
$z[6][4]['type']="top";
$z[7]=Array("global","",1504,1530);
$z[7][4]['name']="cfg_gonggao";
$z[8]=Array("channel","\r\n	<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>\r\n	",1759,1926);
$z[8][4]['row']="3";
$z[8][4]['type']="son";
$z[8][4]['typeid']="5";
$z[9]=Array("global","",1946,1973);
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("channel","\r\n	<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>  | \r\n	",9362,9534);
$z[10][4]['row']="4";
$z[10][4]['type']="son";
$z[10][4]['typeid']="11";
$z[11]=Array("flink","  [field:link /]  ",9635,9713);
$z[11][4]['titlelen']="20";
$z[11][4]['row']="50";
$z[11][4]['type']="text";
$z[12]=Array("global","",9861,9885);
$z[12][4]['name']="cfg_beian";

?>