<?php
$z[0]=Array("include","",463,498);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",536,568);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("list","\r\n<div id=\"case\">\r\n<div class=\"case_pic\"><a href='[field:arcurl/]'target=\"_blank\" style=\"height:113px; overflow:hidden;\"><img src='[field:picname/]' width=\"160\" height=\"120\" style=\"border:0px solid #CCCCCC;\" /></a></div><div class=\"case_tit\"><a href='[field:arcurl/]' target=\"_blank\">[field:title/]</a></div>\r\n</div>\r\n",895,1251);
$z[2][4]['pagesize']="16";
$z[3]=Array("pagelist","",1354,1431);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="7";
$z[4]=Array("global","",1523,1555);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("channel","\r\n<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n",1613,1761);
$z[5][4]['typeid']="5";
$z[5][4]['type']="son";
$z[5][4]['row']="3";
$z[6]=Array("include","",1781,1817);
$z[6][4]['filename']="right.htm";
$z[7]=Array("include","",1838,1875);
$z[7][4]['filename']="footer.htm";

?>