<?php
$z[0]=Array("include","",463,498);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",536,568);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("list","\r\n<li><b>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</b><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n",895,1044);
$z[2][4]['pagesize']="16";
$z[3]=Array("pagelist","",1147,1224);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="7";
$z[4]=Array("global","",1316,1348);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("channel","\r\n<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n",1406,1555);
$z[5][4]['typeid']="11";
$z[5][4]['row']="4";
$z[5][4]['type']="son";
$z[6]=Array("include","",1575,1611);
$z[6][4]['filename']="right.htm";
$z[7]=Array("include","",1632,1669);
$z[7][4]['filename']="footer.htm";

?>